@startuml Models

namespace Repository #ECEFF4 {
    class ReminderRepositoryProtocol <<P, #ffccee)>>
    class ReminderRepository  <<S, #ffeecc)>>
    class ReminderDTO
    ReminderRepository ..|> ReminderRepositoryProtocol
    ReminderRepository --> ReminderDTO: 生成
    ReminderRepositoryProtocol -r[hidden]-> ReminderDTO
    ReminderDTO -d-> Model.Reminder: 　変換　
}

namespace Model #ECEFF4 {
    class Reminder <<S, #ffeecc)>>
    class NotificationDateCalculator <<S, #ffeecc)>> #FFE5FF
    Reminder -r[hidden]-> NotificationDateCalculator
    NotificationDateCalculator o-- Util.DateProviderProtocol
    NotificationDateCalculator -r[hidden]-> Util.DateProvider
}

namespace Util #ECEFF4 {
    class DateProviderProtocol <<P, #ffccee)>>
    class DateProvider <<S, #ffeecc)>>
    DateProvider ..|> DateProviderProtocol
}

note bottom of Model.NotificationDateCalculator #FFE5FF {
    単体テストあり
}
