@startuml Models

namespace ReminderListView.Model #FFFFEC {
    class ReminderListProtocol <<P, #ffccee)>>
    class ReminderList #FFE5FF
    class ReminderSorterProtocol <<P, #ffccee)>>
    class ReminderSorter  <<S, #ffeecc)>>
    class ReminderListValidatorProtocol <<P, #ffccee)>>
    class ReminderListValidator  <<S, #ffeecc)>>
    class OldReminderRemoverProtocol <<P, #ffccee)>>
    class OldReminderRemover  <<S, #ffeecc)>> #FFE5FF
    ReminderList "1" o-- "*" Model.Reminder
    ReminderList *-- Repository.ReminderRepositoryDelegate
    ReminderList *-- ReminderSorterProtocol
    ReminderList *-- ReminderListValidatorProtocol
    ReminderList .u.|> ReminderListProtocol
    ReminderSorter ..|> ReminderSorterProtocol
    ReminderListValidator ..|> ReminderListValidatorProtocol
    OldReminderRemover ..|> OldReminderRemoverProtocol
    OldReminderRemoverProtocol --> ReminderListProtocol : 引数
}
namespace ReminderListView.Controller #FFFFEC {
    class ReminderListViewController <<UIViewController>>
    class NotificationHandlerProtocol <<P, #ffccee)>>
    class NotificationHandler <<S, #ffeecc)>>
    ReminderListViewController o-- ReminderListView.Model.ReminderListProtocol
    ReminderListViewController *- ReminderListView.View.ReminderListView
    ReminderListViewController *- ReminderListView.View.NoReminderView
    ReminderListViewController o-- NotificationHandlerProtocol
    ReminderListViewController o-- Model.NotificationDateCalculator
    ReminderListViewController o--- Util.DateProviderProtocol
    ReminderListViewController o-- ReminderListView.Model.OldReminderRemoverProtocol
    ReminderListViewController -u-> ReminderEditView.Controller.ReminderEditViewController: 画面遷移
    NotificationHandler ..|> NotificationHandlerProtocol
}
namespace ReminderListView.View #FFFFEC {
    class ReminderListView <<UIView>>
    class NoReminderView <<UIView>>
    ReminderListView -[hidden]-> NoReminderView
}

' 依存先
namespace Util #ECEFF4 {
    class DateProviderProtocol <<P, #ffccee)>>
}
namespace Repository #ECEFF4 {
    class ReminderRepositoryDelegate <<P, #ffccee)>>
}
namespace Model #ECEFF4 {
    class Reminder <<S, #ffeecc)>>
    class NotificationDateCalculator <<S, #ffeecc)>> #FFE5FF
}
namespace ReminderEditView.Controller #E9FFFF {
    class ReminderEditViewController <<UIViewController>>
}
